[build]
builder = "nixpacks"
buildCommand = "pip install -r server/requirements.txt"

[deploy]
startCommand = "cd server && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on-failure"